package smartlife.monitorwearables.entities;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see
 */
public class DaoSession  {



}
